### ISSUE TITLE
join-chat

### ISSUE THREAD

**Issue by obvoso** [42-pingpong/backend#102]
**1. 메인화면에 채팅방 목록**

참여중인 채팅방만 보여주기로 했잖아요
그러면 기존 채팅방 사람들한테 초대받는 방법 말고는 다른 채팅을 못보는데
채팅방 생성할 때 말고도 채팅방 안에서 유저 초대 기능 만들어야할 거 같은데 만들까요?

**Comment by obvoso** [comment]
**2. 채팅방에 뉴비가 들어왔을 때, user의 정보가 변경되었을 때** 

기존에 만들어진 채팅룸에 새 유저가 들어왔을 때,
유저가 강퇴되거나 로그아웃하거나 등 state가 변경되었을 때
기존에 그 방에 있던 유저들이 뉴비가 들어온 사실을 알아야하는데

<img width="497" alt="스크린샷 2023-08-14 오전 2 13 29" src="https://github.com/42-pingpong/backend/assets/97217713/14dd2894-317b-4eca-aad1-f83d72ad4c48">

여기서 
`client.emit('join-room', resPonse);`
이부분을 .to(roomId).emit 으로 변경하면 되는건가요? 아니면 해주세여..

**Comment by obvoso** [comment]
@koreanddinghwan

**Comment by koreanddinghwan** [comment]
> **1. 메인화면에 채팅방 목록**
> 
> 참여중인 채팅방만 보여주기로 했잖아요 그러면 기존 채팅방 사람들한테 초대받는 방법 말고는 다른 채팅을 못보는데 채팅방 생성할 때 말고도 채팅방 안에서 유저 초대 기능 만들어야할 거 같은데 만들까요?

아...이건 추가기능으로하죠
