### ISSUE TITLE
chat room password invalid

### ISSUE THREAD

**Issue by obvoso** [42-pingpong/backend#106]
<img width="485" alt="스크린샷 2023-08-14 오후 4 35 12" src="https://github.com/42-pingpong/backend/assets/97217713/590aa7b3-ed8b-42c0-a25e-c646443c4b1c">

**Comment by obvoso** [comment]
console찍어보면 groupChat.password 가 undefined이래요

**Comment by koreanddinghwan** [comment]
ㅈㅅ...
바로고칠게요

**Comment by obvoso** [comment]
<img width="517" alt="스크린샷 2023-08-14 오후 4 38 05" src="https://github.com/42-pingpong/backend/assets/97217713/9602acf3-9787-4ef6-99b1-1d6d31c166b8">

여기 to.emit으로 하면 처음 방 들어갈 때  client한테는 emit안되는 거 같아서 
위에 따로 클라한테 에밋 해줬어여 
이것두 추가해주세여..
