### ISSUE TITLE
profile edit API요청

### ISSUE THREAD

**Issue by obvoso** [42-pingpong/backend#34]
@koreanddinghwan 
천천히 해주세요 감사합니다

<img width="390" alt="스크린샷 2023-08-03 오전 3 17 24" src="https://github.com/42-pingpong/backend/assets/97217713/2f25f24b-7bee-436a-a528-d10359054977">

1. profile image

formData로 보내면 바이너리파일로 넘어간대요
response에 uri달아주시면 프로필 수정 후 다시 user/me 요청 안해도 될 거 같아요

2. nickName, intro

이미지 빼고 닉네임, 자기소개를
nickName:string,
selfIntoroduction: string
으로 보낼게요

3. 닉네임 중복 확인

추가로 닉네임 중복확인 해야할 거 같은데 중복확인할 수 있는 api도 하나만 만들어주시면 감사하겠습니다
번거로우면 서브밋 보내고 response로 알려주세요 프론트에서 alert창 띄우던가 할게요

**Comment by koreanddinghwan** [comment]
2.

**Comment by koreanddinghwan** [comment]
patch /api/user/{id} 에서 partial 객체로 updateDto보내면 부분적 update됩니다.

**Comment by koreanddinghwan** [comment]
1. nickName만 dto에 실어 보내시면 그걸로 해당 유저의 nickName을 수정하려고 시도합니다.
2. 중복된 닉네임인 경우, conflictException을 뱉습니다.

1. email도 동일합니다.
