### ISSUE TITLE
check alarms

### ISSUE THREAD

**Issue by koreanddinghwan** [42-pingpong/backend#43]

**Comment by koreanddinghwan** [comment]
```typescript
socket.emit("checked-alarm", {
requestId: number
})
```

**Comment by koreanddinghwan** [comment]
생각해보니까 알람 한번에 배열로 받아야하지않나?

**Comment by koreanddinghwan** [comment]
```typescript
socket.emit("checked-alarm", 
[
{
requestId: 1
},
{
requestId: 2
}
]
)
```

**Comment by obvoso** [comment]
아까 에러가 나는 배열로 선언했는데 객체로 줘가지고 난거긴해 

받을 객체 1개여서 그런줄알았는데

**Comment by koreanddinghwan** [comment]
이거 아까 그거랑 다른건디

**Comment by obvoso** [comment]
ㅈㅅ 노트북으로 다시볼게

**Comment by koreanddinghwan** [comment]
사용자가 알람버튼 누르면 확인안했던 알람들 읽었다고 소켓에 보내줘야항께

**Comment by obvoso** [comment]
아 엉 저거 배열로 보낼랬어

`socket.emit("checked-alarm", 
[
 {
requestId: 1
},
{
requestId: 2
}
]
)`

일캐 보낼게여

**Comment by koreanddinghwan** [comment]
오케이~~

**Comment by obvoso** [comment]
같은 브랜치에 했습니담

**Comment by koreanddinghwan** [comment]
> 아 엉 저거 배열로 보낼랬어
> 
> 
> 
> `socket.emit("checked-alarm", 
> 
> [
> 
>  {
> 
> requestId: 1
> 
> },
> 
> {
> 
> requestId: 2
> 
> }
> 
> ]
> 
> )`
> 
> 
> 
> 일캐 보낼게여

엥 근데 이거 그냥 유저아이디만 있으면 될듯?

**Comment by obvoso** [comment]
requestId가 pk라서 저렇게 보내란 거 아니었나요

요청받은 아이디 보내면 컬럼 다 날리게요?

**Comment by koreanddinghwan** [comment]
저거 이벤트 발생시점이 노티버탄 누르면 발생하는거 맞져?

**Comment by obvoso** [comment]
엉 지금은 노티 버튼 활성화 되고난 뒤에 누르면 보내는걸로 해놨어

**Comment by koreanddinghwan** [comment]
낼 집가서 확인해보겠슴다
