### ISSUE TITLE
accept friend request alarm

### ISSUE THREAD

**Issue by koreanddinghwan** [42-pingpong/backend#44]

**Comment by koreanddinghwan** [comment]
<img width="451" alt="스크린샷 2023-08-04 23 15 31" src="https://github.com/42-pingpong/backend/assets/76278794/4f257a2d-6837-41f7-ad82-c40adb4e2782">

**Comment by koreanddinghwan** [comment]
@obvoso

**Comment by obvoso** [comment]
죄송합니다.. 가서 바로 고칠게요

**Comment by koreanddinghwan** [comment]
<img width="447" alt="스크린샷 2023-08-04 23 16 43" src="https://github.com/42-pingpong/backend/assets/76278794/48862234-742c-437f-8029-ae883e5be682">

리퀘스트 오는거 확인함용

**Comment by obvoso** [comment]
고쳤어요 닫아주세여
